### PR TITLE
use memoized ironmeta

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by notwaldorf** [comment]
@garlicnation all these tests are angry :(

**Comment by notwaldorf** [comment]
@garlicnation ping! what's the status of this PR?

**Comment by garlicnation** [comment]
Will update from the office tomorrow.

**Comment by notwaldorf** [comment]
I'm going to close this PR since the tests are super angry after it. @garlicnation please re-open if it's ready for another look.

**Pull request closed without merging**
