### PR TITLE
Type _validator property for closure Polymer pass

### PR DESCRIPTION
**Pull request by mgiuffrida**

### CODE REVIEW

**Comment by mgiuffrida** [comment]
@notwaldorf could you merge and increment version please?

**Comment by danbeam** [comment]
/cc @rictic as this is mainly to fix a compiler error:
https://build.chromium.org/p/tryserver.chromium.linux/builders/closure_compilation/builds/61/steps/compile/logs/stdio

**Comment by rictic** [comment]
LGTM

**Comment by rictic** [comment]
LGTM

**Pull request merged**
